# Generated by Django 3.2 on 2021-04-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_students_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.departments'),
            preserve_default=False,
        ),
    ]
